### ISSUE TITLE
Redirecionamento pos-login com logica de primeiro login

### ISSUE THREAD

**Issue by KassioL2L** [portal-ciclismo/front#77]
Faça o redirecionamento do usuário após logado, e crie uma logica de se caso for o primeiro login o redirecionamento aconteça para uma pagina de complete cadastro, e caso não seja o primeiro login, o redirecionamento acontece para a pagina de perfil do usuario

**Comment by guirmsilva** [comment]
eu vou direcionar pra home nos dois casos. não tem como saber se é o primeiro login do usuário ou não. na página de cadastro precisamos cobrar os dados obrigatórios do usuário pra não ter que fazer isso. quando criarem a página de perfil do usuário eu ajusto novamente
